[default.extend-words]
# Git commit hashes that typos flags as potential typos
ba = "ba"  # Part of commit hashes like e28e0ba
# ANSI escape codes in snapshots make is_main/is_current/is_previous look like "mis"
mis = "mis"
